language: node_js
node_js:
  - 12
cache:
  yarn: true
  directories:
    - node_modules
branches:
  except:
    - /^v\d+\.\d+\.\d+$/ 
install:
  - yarn install --frozen-lockfile
  - npm install -g codecov
script:
  - yarn lint
  - yarn test
  - codecov
after_success:
  - test $TRAVIS_BRANCH = "master" && ./node_modules/.bin/semantic-release --ci --debug